---
remi_repo_url: "http://rpms.remirepo.net/enterprise/remi-release-{{ ansible_distribution_major_version }}.rpm"
remi_repo_gpg_key_url: "http://rpms.remirepo.net/RPM-GPG-KEY-remi"

# if you want to add more then one repo you should change task
remi_repo_repos_to_enable: "remi-php72"