---
# Variable configuration.
- include_tasks: variables.yml

# Execute procedures before setup (add and enable oracle mysql repo)
# now it'll be executed only for redhat and will work only for 7th version
- include_tasks: pre_tasks.yml

# Setup/install tasks.
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: setup-Archlinux.yml
  when: ansible_os_family == 'Archlinux'

- name: Check if MySQL packages were installed.
  set_fact:
    mysql_install_packages: "{{ (rh_mysql_install_packages is defined and rh_mysql_install_packages.changed)
      or (deb_mysql_install_packages is defined and deb_mysql_install_packages.changed)
      or (arch_mysql_install_packages is defined and arch_mysql_install_packages.changed) }}"
     
# TODO I could check availability of /root/.my.cnf config for vanilla 5.7
#      before installation and add more complex rules to define was it first
#      installation or not. But I don't do it untill it will be definitely need me
- name: Check mysql config in root directory. Is this a first run after install?
  stat:
    path: "{{ mysql_root_home }}/.my.cnf"
  register: mysql_root_client_conig

# Configure MySQL.
- include_tasks: configure.yml

# we have to do special after install procedures if oracle/vanilla mysql >= 5.7 version installed
- include_tasks: secure-installation_modern_vanilla.yml
  when: >
    ansible_os_family == "RedHat"
    and ('5.7.' in mysql_cli_version.stdout or '8.0.' in mysql_cli_version.stdout)
    and not mysql_root_client_conig.stat.exists

# after configure and setting up root password it's possible to disable password validation
# not earlier (cause it'll failed)
# to disable validation you should check and delete/comment out any 'validate-password'
# directive in any file and add 'validate-password = OFF' and then restart the mysql server
# ! YES it's impossible to set simple root password after installation
# cause any you can do with temporary password is to change it.
#
# also after successfull installation it's possible to add one more .cnf file with
# validate-password option BUT you still need to restart server
    
# if we just changing configuration or root/user password 
# in vanilla mysql >= 5.7 we doing everything as usual
- include_tasks: secure-installation.yml
- include_tasks: databases.yml
- include_tasks: users.yml
- include_tasks: replication.yml
